sudo: required
dist: bionic
language:
  - cpp
#  - android

addons:
  apt:
    sources:
      github-git-lfs-bionic
    packages:
      git-lfs
      
cache:
  - apt
  - directories:
    - model
    - Package

compiler:
  - g++

os:
  - unix

#jdk:
  #- oraclejdk8
  #- oraclejdk9
  #- openjdk8

#android:
#  components:
#    - platform-tools
#    - build-tools-28.0.3
#    - android-24
#    - ndk-bundle
#    - platforms-24

addons:
  ssh_known_hosts:
    - github.com
    - frs.sourceforge.net

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBIT_BUILD_THIRDLIBRARY="TRUE"
    - QMAKE=qmake

  matrix: 
    # BUILD_ARCH qt 大于等于 5.14.0 可选（arm64-v8a armeabi-v7a x86_64 x86）组合
    #- BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a x86" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.14 QT_VERSION=5.14.0 ANDROID_API=android-24 DOWNLOAD_QT=TRUE  GENERATORS="Unix Makefiles"
    - BUILD_TARGERT="android" BUILD_ARCH="armeabi-v7a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.13 QT_VERSION=5.13.2 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles" DOWNLOAD_THIRDLIBS_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.2.9/android_arm_v0.2.9_in_linux.tar.gz
    - BUILD_TARGERT="android" BUILD_ARCH="arm64-v8a" ANDROID_ARM_NEON=ON QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles" DOWNLOAD_THIRDLIBS_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.2.9/android_arm64_v0.2.9_in_linux.tar.gz
    - BUILD_TARGERT="android" BUILD_ARCH="x86" QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 ANDROID_API=android-24 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles" DOWNLOAD_THIRDLIBS_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.2.9/android_x86_v0.2.9_in_linux.tar.gz
  
    # DOWNLOAD_QT:
    #     APT: Use apt to install from ubuntu source;
    #     TRUE: download from download.qt.io
    #     FALSE: install from https://launchpad.net/~beineri
    - BUILD_TARGERT="unix" DOWNLOAD_QT=APT GENERATORS="Unix Makefiles"
    
    - BUILD_TARGERT="unix" QT_VERSION_DIR=512 QT_VERSION=5.12.3 DOWNLOAD_QT=FALSE GENERATORS="Unix Makefiles" DOWNLOAD_THIRDLIBS_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.2.9/unix_x86_64_v0.2.9.tar.gz
    - BUILD_TARGERT="unix" QT_VERSION_DIR=511 QT_VERSION=5.11.3 DOWNLOAD_QT=FALSE STATIC=ON GENERATORS="Unix Makefiles" DOWNLOAD_THIRDLIBS_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.2.9/unix_x86_64_v0.2.9.tar.gz

    - BUILD_TARGERT="unix" BUILD_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.6 DOWNLOAD_QT=TRUE GENERATORS="Unix Makefiles" DOWNLOAD_THIRDLIBS_URL=https://github.com/KangLin/RabbitThirdLibrary/releases/download/v0.2.9/unix_x86_64_v0.2.9.tar.gz

before_install:
  #- sudo apt-get update -y -qq
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - sudo apt-get install -y -qq xvfb xpra
  - sudo Xvfb :99 -ac &
  - export DISPLAY=:99.0
  - mkdir ${SOURCE_DIR}/Tools
  - export VERSION="v0.0.4"

install:
  - cd ${SOURCE_DIR}
  #- /bin/bash ci/backgroud_echo.sh &
  - git clone https://github.com/KangLin/RabbitCommon.git
  - export RabbitCommon_DIR="`pwd`/RabbitCommon"
  - bash ci/build-install-tools.sh #> /dev/null
#  - |
#    if [ "$BUILD_TARGERT"="unix" -a -z "$RABBIT_ARCH" ]; then
#        source /opt/qt511/bin/qt511-env.sh
#    fi

before_script:
  - cd ${SOURCE_DIR}

script:
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

notifications:
  email: kl222@126.com
  on_success: never  # [always|never|change]
  on_failure: always

#deploy:
#  - provider: releases
#    api_key:
#      secure: ALZWWdQlmi0gJ5Gs9gjX4waV4JYvZAFogN6oUCJayWYkCvME/z1QSxMERuZhRM0F4K2Kt8LWK2ozp18OEtonNQJ81ZELbZRYMQwl4C3Cmfhnywyn4UgiU3CLEQ3Dn25iLqHy7QhaS6BWyISxVQxrsEhFkc0tLDODwk45tibiniIpTtBtTB9Tx85p8FEfdOHUCNxhVtW9zF0LjdWxD569HEzpKDi8c4naNCDVvbBA9r2voQqt3NkNsCNz10vxyV+xO8uJIs1/K5Mj6Gnd+UaUtSDnVTUKCZatcge5OGpu9TcYbH5yLuhlTifVtYmhmK3YeAmte6uNlD6WYIdpSTMJLQ8Lgc2WE+2mj0G16afWtY9ajTqVUlJEa1R078gCnFG4YeYjUYIZhFq/u0U16Ga95RvHAZlQNVcyDLb/Mwt6QyJJdWRNHzsm1sY6mwhXKRwAMGvPl9RTWl6JJdFT5wcPYIzPL9+Y6k6ZhkdI6kWEzA7HYUbA1mLiF6Q8h+ezKnb10KiPEAFU4NNUmf3RKMwolRSTN/TkiZCRIVsPKnkLgS5LzTf6s0rGBZ2g5vWo1fDsigDPBJRE27742pPDXXMt82CySThq3lKJFwQsGObLg1z2H8XbvDkImVIVOK98oW2a/7aXX28/0LjWE2tdV83p1ho5DvyTlGZio+fqk0qmfsw=
#    file: "$TRAVIS_BUILD_DIR/../tasks_${VERSION}_amd64.deb "
#    skip_cleanup: true
#    on:
#      tags: true
#      condition: "$BUILD_TARGERT=unix && $QT_VERSION_DIR=512 && $DOWNLOAD_QT=FALSE"
